[package]
name = "glfw_test"
version = "0.1.0"
authors = ["Simon Rönnberg <simon.ronnberg@codemill.se>"]

[dependencies]
glfw = "*"
remawin = { path = "../../remawin/" }
remawin_source_glfw = { path = "../../remawin_source_glfw/" }
log = "*"
