contexts:
  - id : default
    mappings:
      - raw_type : Key
        raw_args :
          action : Release
          keycode : Escape
        action: Close
      - raw_type : Key
        raw_args :
          keycode : W
        action : MoveForward
      - raw_type : Key
        raw_args:
          keycode: Key1
          action: Release
          modifier: ALT
        action : FireAbility1
      - raw_type : Motion
        raw_args : {}
        action : RotateDirection
  - id : ui
    mappings:
      - raw_type : Char
        raw_args : {}
        action : Text
