contexts:
  - id : default
    mappings:
      - raw:
          raw_type : Key
          args :
            action : Release
            keycode : Escape
        mapped:
          constant_id : Close
          args : []
      - raw :
          raw_type : Key
          args :
            keycode : W
        mapped :
          constant_id : MoveForward
          args : []
      - raw :
          raw_type : Key
          args:
            keycode: Key1
            action: Release
            modifier: ALT
        mapped :
          constant_id : FireAbility1
          args:
            - CursorPosition
      - raw :
          raw_type : Motion
          args : {}
        mapped :
          constant_id : RotateDirection
          args : []
  - id : ui
    mappings:
      - raw:
          raw_type : Char
          args : {}
        mapped:
          constant_id : Text
          args:
            - Value
