[package]
name = "glfw_test"
version = "0.1.0"
authors = ["Simon Rönnberg <simon.ronnberg@codemill.se>"]

[dependencies]
glfw = "*"
remawin = { path = "../../remawin/" }
remawin_glfw_mapper = { path = "../../remawin_glfw_mapper/" }
log = "*"
