[package]
name = "remawin_source_glutin_external"
version = "0.1.0"
authors = ["Simon Rönnberg <simon.ronnberg@codemill.se>"]

[dependencies]
glutin = "*"
remawin = { path = "../remawin/" }
remawin_glutin_mapper = { path = "../remawin_glutin_mapper/" }
time = "*"
