contexts:
  - id : default
    mappings:
      - raw:
          raw_type : Key
          args :
            action : Release
            keycode : Escape
        mapped: Close
      - raw :
          raw_type : Key
          args :
            keycode : W
        mapped : MoveForward
      - raw :
          raw_type : Key
          args:
            keycode: Key1
            action: Release
            modifier: ALT
        mapped : FireAbility1
      - raw :
          raw_type : Motion
          args : {}
        mapped : RotateDirection
  - id : ui
    mappings:
      - raw:
          raw_type : Char
          args : {}
        mapped: Text
