[package]
name = "rebindit-examples"
version = "0.1.0"
authors = ["Simon Rönnberg <simon.ronnberg@codemill.se>"]

[dependencies]
glutin = "*"
rebindit = { path = "../rebindit/" }
serde = "*"
serde_derive = "*"
log = "*"
env_logger = "*"

[[example]]
path = "basic.rs"
name = "basic"

[[example]]
path = "complex.rs"
name = "complex"
