[package]
name = "glfw_test"
version = "0.1.0"
authors = ["Simon Rönnberg <simon.ronnberg@codemill.se>"]

[dependencies]
glutin = "*"
input = { path = "../.." }
glutin_input_source = { path = "../../sources/glutin/" }
log = "*"
